Consider the below code to answer further questions:

import numpy as np
variables_list = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = variables_list)

Q1. Is there any difference in the data type of variables_list and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data types of variables_list and array_list

In [2]:
import numpy as np

variables_list = ['1', '2', '3', '4', '5']
array_list = np.array(object=variables_list)


print("Data type of list_:", type(variables_list[0]))
print("Data type of array_list:", type(array_list[0]))

Data type of list_: <class 'str'>
Data type of array_list: <class 'numpy.str_'>


Q2. Write a code to print the data type of each and every element of both the variables_list and
arra_list.

In [3]:
import numpy as np

variables_list = ['1', '2', '3', '4', '5']
array_list = np.array(object=variables_list)

print("Data types of elements in list_:")
for element in variables_list:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = variables_list, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Yes, there will be a difference in the data type of the elements in array_list after the modification.

In [5]:
import numpy as np

variables_list = ['1', '2', '3', '4', '5']
array_list = np.array(object=variables_list, dtype=int)


print("Data types of elements in variables_list:")
for element in variables_list:
    print(type(element))


print("\nData types of elements in modified array_list:")
for element in array_list:
    print(type(element))

Data types of elements in variables_list:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in modified array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [6]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)


shape_of_array = num_array.shape
size_of_array = num_array.size

print("Shape of num_array:", shape_of_array)
print("Size of num_array:", size_of_array)

Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [7]:
import numpy as np

zeros_array = np.zeros((3, 3))

print("Array of 3x3 matrix containing zeros:")
print(zeros_array)

Array of 3x3 matrix containing zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
import numpy as np

identity_matrix = np.eye(5)

print("Identity matrix of shape (5, 5):")
print(identity_matrix)

Identity matrix of shape (5, 5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
